<!-- begin project_meta_override block -->
    <meta name="cmg:siteId" content="austin360">
    <meta name="cmg:siteType" content="free">
    <meta name="cmg:siteDomain" content="austin360.com">
    <meta name="cmg:product" content="www.austin360.com">
    <meta name="cmg:siteSection" content="Lifestyles">
    <meta name="cmg:category" content="Fitness">
    <meta name="cmg:subcategory" content="choose_your_race">
    <meta name="cmg:mainSection" content="/recreation">
    <meta name="cmg:topics" content="aasinteractive, choose_your_race">
    <meta name="cmg:byline" content="pam leblanc, christian mcdonald">
<!-- end project_meta_override block -->